# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Martin Haug
email: mhaug&#64;<span class="hidden">null</span>live.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
browsehappy: > # this means to ignore newlines until "baseurl:"
  You are using an <strong>outdated</strong> browser.
  Please <a href="http://browsehappy.com/">upgrade your browser</a>
  to improve your experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_profile_id: martin.haug1
twitter_username: reknih
github_username:  reknih
linkedin_profile:  martin-ernst-haug-074021135
repository: reknih/reknih.github.io

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Martin Haug"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Martin Haug"